--- #YAML:1.0
name:               Games-RolePlay-MapGen
version:            1.4002
abstract:           ~
author:  []
license:            LGPL
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Algorithm::Diff:      0
    Data::Dump:           0
    Data::Dumper:         0
    File::Slurp:          0
    GD:                   0
    Gtk2:                 0
    Gtk2::Ex::Dialogs:    0
    Gtk2::Ex::Simple::Menu:  0
    HTTP::Status:         0
    List::Util:           0
    Math::Round:          0
    Math::Trig:           0
    perl:                 5.008
    POE:                  0
    POE::Component::Server::HTTP:  0
    Storable:             0
    Test:                 1.25
    Tie::IxHash:          0
    XML::Parser:          0
    XML::Simple:          0
    XML::XPath:           0
resources:
    repository:  http://github.com/jettero/grm/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - map
    - editor
    - visicalc
    - grm
