--- #YAML:1.0
name:                Games-RolePlay-MapGen
version:             1.2.15
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Algorithm::Diff:               0
    File::Slurp:                   0
    Software::License::LGPL_2_1:   0
    Test:                          1.25
    Tie::IxHash:                   0
    XML::Parser:                   0
    XML::Simple:                   0
    XML::XPath:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
