--- #YAML:1.0
name:                Games-RolePlay-MapGen
version:             1.2.14
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Algorithm::Diff:               0
    File::Slurp:                   0
    Software::License::LGPL_2_1:   0
    Test:                          1.25
    Tie::IxHash:                   0
    XML::Parser:                   2.36
    XML::Simple:                   0
    XML::XPath:                    1.13
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
